name: Update codes on OpenVPN server 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Codes
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.OPENVPN_SERVER_1_HOST }}
          username: ${{secrets.OPENVPN_SERVER_1_USERNAME}}
          password: ${{secrets.OPENVPN_SERVER_1_KEY}}
          script: ls ${{github.workspace}}/.github

